version: "2"
plugins:
  duplication:
    enabled: true
    exclude_patterns:
    - "task_manager/**/urls.py"
    - "task_manager/labels/migrations/"
    - "task_manager/labels/forms.py"
    - "task_manager/labels/models.py"
    - "task_manager/labels/views.py"
    - "task_manager/statuses/forms.py"
    - "task_manager/statuses/views.py"
    - "task_manager/tasks/filters.py"
