# Generated by Django 4.1.5 on 2023-02-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['id'], 'verbose_name': 'Label', 'verbose_name_plural': 'Labels'},
        ),
    ]
