# Generated by Django 4.1.5 on 2023-02-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['id'], 'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
    ]
